### ISSUE TITLE
SciPy-style OptimizeResult

### ISSUE THREAD

**Issue by jungtaekkim** [acerbilab/pybads#45]
I think that you wanted to follow the style of the SciPy's OptimizeResult.

If needed, you can mention that it is a similar feature of the OptimizeResult in SciPy.

It will help users understand how they would use this feature.

https://github.com/acerbilab/pybads/blob/1bee482a7b53526aa3acc177c10707c28490b7ea/pybads/bads/optimize_result.py#L8

**Comment by GurjeetSinghSangra** [comment]
Ok thank you for your feedback, I just added the reference in the code as part of the documentation of the class.
